name: Run unit tests

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

env:
  # Stop wasting time caching packages
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  # Disable sending usage data to Microsoft
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  test:
    runs-on: windows-latest
    name: Run unit tests
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: true
      
      # for now binaries are included, uncomment on remove
      #- name: Download dependencies
      #  run: .\download.ps1
      #  shell: powershell
      #  
      #- name: Build lapack
      #  run: .\build.ps1
      #  shell: powershell
      #  
      - name: Setup .NET Core 3.1 @ Latest
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: '3.1.x'
          
      - name: Create build
        run: dotnet build "src/Lapack.Net" -c Release --force
      
      - name: Run Unit Tests
        run: dotnet test "src/Lapack.Net.UnitTests" -c Release
